### ISSUE TITLE
use stream2es to index wikipedia

### ISSUE THREAD

**Issue by asmaElk** [elasticsearch/stream2es#73]
hello,
I have problem with running this command on windows

`  % stream2es wiki --target http://localhost:9200/tmp --log debug
create index http://localhost:9200/tmp
stream wiki from http://download.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2
^Cstreamed 1158 docs 1082 bytes xfer 15906901 errors 0`
my error is : 

> stream2es is not  an intern command

**Comment by Crazybus** [comment]
Looking at https://github.com/elastic/stream2es windows appear to be supported. Assigning to @drewr

**Comment by drewr** [comment]
Have you made the file executable?

**Comment by asmaElk** [comment]
I have stream2es installed and I use the path where it is installed to run
the commande in the cmd line commande to index wikipedia
I'm I missing something ?

2018-05-03 18:04 GMT+00:00 Drew Raines <notifications@github.com>:

**Comment by drewr** [comment]
Not sure if there's anything we can do here. stream2es doesn't work with later versions of Elasticsearch anyway.
